CREATE DATABASE projectmanagerapp;

CREATE TABLE TASK (
	task_id BIGINT(10) NOT NULL AUTO_INCREMENT,
	parent_task VARCHAR(50) NULL DEFAULT NULL,
	task VARCHAR(50) NULL DEFAULT NULL,
	priority VARCHAR(2) NULL DEFAULT NULL,
	start_date DATE NULL DEFAULT NULL,
	end_date DATE NULL DEFAULT NULL,
	status VARCHAR(10) NULL DEFAULT NULL,
	parent_id BIGINT(10) NULL DEFAULT NULL,
	project_id BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (task_id),
	CONSTRAINT FK_TASKS FOREIGN KEY (parent_id) REFERENCES TASK (task_id)
);

CREATE TABLE PARENT_TASK (
    parent_id INT NOT NULL AUTO_INCREMENT,
    parent_task VARCHAR(100) NOT NULL,
	project_id BIGINT(10) NULL DEFAULT NULL,
    PRIMARY KEY (parent_id)
);

CREATE TABLE USERS (
    user_id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NULL DEFAULT NULL,
	last_name VARCHAR(50) NULL DEFAULT NULL,
	employee_id BIGINT(10) NULL DEFAULT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE PROJECT (
	project_id BIGINT(10) NOT NULL AUTO_INCREMENT,
	task VARCHAR(50) NULL DEFAULT NULL,
	priority VARCHAR(2) NULL DEFAULT NULL,
	start_date DATE NULL DEFAULT NULL,
	end_date DATE NULL DEFAULT NULL,
	user_id BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (project_id),
	CONSTRAINT FK_PROJECT FOREIGN KEY (user_id) REFERENCES PROJECT (project_id)
);
